name: Deploy Streamlit App to GitHub Pages

# Controls when the action will run
on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest version of the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requierments.txt  # Install from your requirements.txt

    # Step 4: Deploy the Streamlit app to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory where the Streamlit app exists
