name: Deploy Streamlit App to GitHub Pages

on:
  push:
    branches:
      - main  # Only deploy when changes are pushed to the main branch
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requierments.txt

    # Step 4: Build the Streamlit app
    # Streamlit apps are dynamic and don't need a build step, so you can skip this part
    # However, you might want to ensure all files are ready for deployment (e.g., static files)

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # Use gh-pages as the deployment branch
        publish_dir: ./  # This is the directory with the content to be deployed

    # Optional: Clean-up
    - name: Cleanup
      run: |
        rm -rf __pycache__
